### ISSUE TITLE
Major Feedback - 19Jan

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/nawqa-sw-trends#140]
Feedback from Lori:

**Intro pop up**
- [x] 1. In "Learn More", fix the odd characters in the text. (see for example, the 4th paragraph)
- [x] 2. In "Learn More", replace the text about water-quality constituents with the table that is in "Intro pop up.docx".  It has units, etc., that need to be shown.
- [x] 3. In "Learn More", in the aquatic ecology table, change the header "Diatoms" to "Algae (diatoms)".
- [x] 4. In "Learn More", at the very end, remove the paragraph (Trends in the water quality....).  That information has been moved elsewhere. 
- [x] 5. Change the name of tab "Partner Agencies" to "Partner Organizations".
- [x] 6. Move "Other Resources" to the blue tool bar.  Add one more website that is in the latest version of "Web sites.docx". (The new one is under Links to Other Federal Agencies)
- [x] 7. In "Disclaimer", is that the standard disclaimer that we add to web sites with results or data?  The one in CIDA"s SPARROW mapper is "Please note that no endorsement, expressed or implied, is made by the USGS or the U.S. Government of any interpretations or decisions that result from the use of these results, nor shall the fact of distribution constitute any such endorsement, and no responsibility is assumed by the USGS in connection therewith."  Too much?  Maybe we should see what Kevin Breen says.
- [x] 8. Create new tabs "Related U.S. Geological Survey web applications" and "For more detail on this study". Put these tabs before "Disclaimer".  Content for these two tabs is in "Intro pop up.docx".
 
**Constituent Select area**
- [x] 9. Add hover help buttons or link to User Guide for each selection option.
 
**User Guide**
- [x] 10. Remove odd characters in text throughout.
- [x] 11. In "Search, Zoom, Print", under "Opening a site", delete text "See examples below."
- [x] 12. In "Legend", change the screen shot the shows the legend arrows.  You can see the old "pest layer" in the current version.
- [x] 13. In “Legend” (THIS IS A NEW REQUEST FROM ME), add this sentence at the very end, in the last paragraph.  “Likelihood values for nutrients, sediment, salinity, and carbon were determined using the bootstrap approach in Hirsch and others (2013).  Likelihood values for pesticides and aquatic ecology were determined using the p-value reported from the trend test, in the equation 1-(pvalue/2).”
- [x] 14. In "Map selection options", reorder the rows to match the left-hand side of the application.  See "Map Selection Options User Guide text.docx".
- [x] 15. In "Map selection options", most of the text needs to change a bit. See "Map Selection Options User Guide text.docx".  Note also that "Selecting Layers" should change to "Selecting a constituent".
 
**Print**
- [x] 16. The title for all of the aquatic ecology trend results needs to be modified. It starts with "Concentration trend results" or "Load trend results" (I think it depends on the last water-quality selection made before the aquatic ecology selection is made) but it should only read "Trend results for...."
- [x] 16A. Update URL to https://nawqatrends.wim.usgs.gov/swtrends/
- [x] 16B. Change print product title to show (flow normalized) after "Trend results" and before "for" for every title.
 
**Map display**
- [x] 17. Can the default mapping extent be changed just a smidge to automatically display Puerto Rico?
 
**FAQs**
- [x] 18. Remove odd characters in text throughout.
- [x] 19. FAQ #9 says "Blah blah blah can be found here" three times.  Can you add the appropriate hyperlink to the User Guide?  If not, change each occurrence of “here” to “in the User Guide”.
- [x] 20. FAQ #10. The DOI URL is repeated twice in the 3 citations.  Sorry, my bad! They  may need to be update upon public release, but I think for now we can just change them to:
De Cicco, L.A., Sprague, L.A., Murphy, J.C., Riskin, M.L., Falcone, J.A., Stets, E.G., Oelsner, G.P.,  and Johnson, H.M., 2017, Water-quality and streamflow datasets used in the Weighted Regressions on Time, Discharge, and Season (WRTDS) models to determine trends in the Nation’s rivers and streams, 1972-2012: U.S. Geological Survey data release, http://dx.doi.org/10.5066/F7KW5D4H.
 
Ryberg, K.R., Murphy, J.C., Falcone, J.A., Riskin, M.L., Wieben, C.M., and Vecchia, A.V., 2017, Pesticide concentration and streamflow datasets used to evaluate pesticide trends in the Nation’s rivers and streams, 1992-2012: U.S. Geological Survey data release, http://dx.doi.org/10.5066/F7BC3WPC.
 
Zuellig, R.E. and Riskin, M.L., 2017, Ecological community datasets used to evaluate the presence of trends in ecological communities in selected rivers and streams across the United States, 1992-2012: U.S. Geological Survey data release, http://dx.doi.org/10.5066/F7G44ND3.
 
- [x] 21. FAQ #10 change the FQA call out in the first sentence from see FAQ #11 to see FAQ #12.
- [x] 22. FAQ #12 change the FQA call out in the first sentence from see FAQ #13 to see FAQ #14.
- [x] 23. FAQ #20 change the first FQA call out in the third sentence from see FAQ #10 to see FAQ #11. Change the second FAQ call out in the last sentence from see FAQ #12 to see FAQ #13.
- [x] 24. FAQ #21 change the FQA call out in the first bullet from see FAQ #4 to see FAQ #5.
- [x] 25. FAQ #21 change the FQA call out in the fifth and sixth bullets from see FAQ #15 to see FAQ #17.
- [x] 26. FAQ #22 change the FQA call out toward the end from see FAQ #15 to see FAQ #17.
- [x] 27. FAQ #24 check the very end.  I think it is missing a “”…r”
- [x] 28. FAQ #26 Can the URLs made made active with hyperlinks?
 
**Site Info**
- [x] 29. Site information – the site numbers appear to be missing leading zeros.  I think this is only for aquatic ecology.
- [x] 30. Site information – the Agency for pesticides currently shows “undefined”.  That should always be “USGS” for pesticides.
- [x] 31. Trend results table -- I love the table new sort option!  (ok that's not really a comment..)
- [x] 32. Trend results table -- Need to add hover or help buttons with the additional info that I have in "template for table.xlsx" that define the columns. see issue #76 
- [x] 33. Trend results table -- Trend likelihood values should never be negative.  (I think maybe that's just happening with downward trends?  But for all constituents.)  Probably the value is ok, just need to remove the negative sign.
- [x] 34. Trend results table -- Change "Type" to "Metric (flow normalized)" for all aquatic ecology variables.
- [x] 35. Change "n/a" to "Not available" in the 4 confidence interval columns in the trend results table for all aquatic ecology variable.
- [x] 36. Table Download – I don’t think this is working correctly.  First, I got multiple files downloading with a single request.  Second, they didn’t all contain the same information, and some of them were clearly not for the site I was looking at.  I’m not sure what they were.  Related to this (when I was trying to diagnose this issue), it might be a good idea to put site number and site name in every export file.
 
**New Request**
- [x] 37.  Site information – I noticed I didn’t give you drainage areas for pesticide and aquatic ecology sites.  We are also about to publish new (slightly different) drainage areas for some of the other sites.  I’ve attached here a file from James Falcone that has our final drainage areas (still in sq km) for all sites.  Can you merge that in and use these for all constituents?  Look at column E in the attached file sites1530-dec1-2016-short.xlsx.
- [x] 38.  Add watershed boundary when a user selects a site.  (Nick and I talked about this one, and it’s is a second-tier need that he’ll try to get to if time allows after everything else).

**Comment by HansVraga** [comment]
numbers 6 and 8 are related, I'm going to ask Lori for changes there.

**Comment by HansVraga** [comment]
Nick - for num 17 on this list - should we, upon initial page load, try to set the extent to the content? That will set the user's interface to include Puerto Rico...

Otherwise, Lori said we can skip that one too.

**Comment by HansVraga** [comment]
@mitchas for num 9 - they want something like we did in the Legend, a pointer to the User Guide. We can take the same tack (just some small text telling them to go there) or do a link that opens the User Guide Modal directly to the "Map Selection Options" tab.

**Comment by HansVraga** [comment]
@njestes For num 29 - Lori ran into similar issues with the way the site numbers were displayed in the data, we think that might be causing the leading 0's to be dropped. She emailed with updated data so hopefully that can be restored.

**Comment by HansVraga** [comment]
@njestes for num 37 - I warned Lori that data merge may not be straightforward. I think we can ask them to do that merge themselves and give us the result if that is easier than doing it ourselves?

**Comment by njestes** [comment]
@HansVraga i think I can do the data merge without too much trouble, but if it gets sticky, I'll use that "get your data merged for free by Nawqa" card

**Comment by HansVraga** [comment]
Creating new issue for the remaining item. Nice Job @njestes and @mitchas - this thing looked pretty daunting to get through today, but we mostly did (and them some).

**Comment by njestes** [comment]
40 out of 40. check.
