### ISSUE TITLE
Issues Jan 20

### ISSUE THREAD

**Issue by mitchas** [USGS-WiM/nawqa-sw-trends#157]
## Application-wide change

- [x] 1. Change all occurrences of “Legend” to “Explanation”. (In the User Guide > Legend tab, FAQ #9, FAQ #18, and the map interface legend itself).  The screen shot in User Guide > Legend will also need to change as a result.
 
## Intro pop up

- [x] 2. In "Learn More", fix the odd characters in the header of the first table. It should look like: [mg/L, milligrams per liter. kg/year, kilograms per year; μmohs/cm, micromhos per centimeter; N, nitrogen; P, phosphorus; CaCO3, calcium carbonate; S, sulfate.]
- [x] 3. In "Learn More", it looks like the table showing the water-quality constituents is a screen shot maybe?  That’s totally fine, but I think the auto spell check was active for the two occurrences of “desulfinylfipronil” because they are underlined with sqiggly red.
- [x] 4. On the "Partner Organizations" tab, change the first sentence (changes underlined here only so you can find them) to "Long-term water-quality monitoring data from the following organizations were included in this analysis:"
- [x] 5. On the "Partner Organizations" tab, please use the file "list_of_partner_organizations_01202017.xlsx" (column A) and replace the entire list. This will pick up editorial changes from the SPN.
- [x] 6. In the “Related Resources” tab, change the first occurrence of the header “Other Related US Geological Survey (USGS) Information” to read “Related U.S. Geological Survey web applications”.
 
## User Guide
- [x] 7. Remove odd characters in “Navigating the Map” on the “Search, Zoom, Print” tab
- [x] 8. On the “Search, Zoom, Print” tab, and the “More site details” box.  Given the recent changes to the mapper, changes this text to: “Additional details about the graphs are available in the FAQs.  Additional details about the column headers in the table are available by hovering on the help button for each column header.”
- [x] 9. In “Legend”, in the sentence at the very end, add a hyphen to “pvalue” in the equation 1-(p-value/2).
- [x] 10. In "Map selection options", change the first two box titles to “Changing the basemap style” and “Changing or adding map layers”, respectively.  This is a horribly nitpicky editorial thing.
 
## FAQs
- [x] 11. Remove odd characters in text in FAQs #1, #2, #4, #10, #14, #20, #24, #26
- [x] 12. FAQ #26 The hyperlnk for Sprague, L.A., Oelsner, G.P, and Argue, D.M., 2017, Challenges with secondary use of multi-source water-quality data in the United States: Water Research, v. 110, p. 252-261. does not open in a separate tab as all of the others do; it opens in the same tab and so moves you out of the mapper. Is that changeable?
- [x] 13. FAQ #26.  Add the URL for Ryberg, K.R., Vecchia, A.V., Martin, J.D., and Gilliom, R.J., 2010, Trends in pesticide concentrations in urban streams in the United States, 1992–2008: U.S. Geological Survey Scientific Investigations Report 2010–5139, 101 p.  https://pubs.usgs.gov/sir/2010/5139/
 
## Map Interface
- [x] 14. Change capitalization as follows in Legend area: “For more information, see User Guide”. (This will match how it’s written in the Constituent selection area.)
 
## Site Info
- [x] 15.  Site information – Update all sites and constituents with drainage areas from column E in the attached file “sites1530-dec1-2016-short.xlsx”.
- [x] 16. Site information – Sometimes the Agency field is not complete.  When you’re looking in the INFO file, if both the agency1 and agency2 columns are populated, they both need to be shown on the Site information tab in the “Agency” field.  Maybe separate the agency names by a / to match the respective designation in Data source. So, for example, site 01541000_4673267 under Total Phosphorus would have Data source “NWIS/Agency” and Agency “U.S. Geological Survey/ Pennsylvania Department of Environmental Protection”.
- [x] 17. Trend results table – I love the new hover feature.  A couple of text changes are needed now. 
    - [x] (a) Type column – change the text to “Concentration is the amount of the constituent in the stream.  Load is the mass of the constituent transported past the sampling point in a stream during a period of time.  A metric is an index calculated to represent a specific characteristic of aquatic communities.  Changes over time in water-quality concentration and load and changes in aquatic ecology-metrics can be strongly influenced by random and systematic variations in streamflow.  Flow normalization removes the variation in concentration, load, or metric that is due to variations in streamflow.  As a result, concentration and load trends are flow normalized and aquatic ecology metric trends are flow normalized.  See FAQ #17 for more information.”
    - [x] (b) Trend likelihood column – change the FAQ call out from FAQ #13 to FAQ #18.
    - [x] (c) Trend likelihood column – remove the last sentence of text. (“provide a hyperlink here if it makes sense)
    - [x] (d) Lower confidence interval on the trend, in percent column – add a hover with the same text that is currently used for the column Upper confidence interval on the trend, in original units
    - [x] (e) Upper confidence interval on the trend, in percent column – change to the same text that is currently used for the column Upper confidence interval on the trend, in original units
    - [x] (f) Trend in original units – change the text to “The original units for each constituent and type can be found in About -> Learn More. Trends are reported for the full tend period.  They are not reported on a per year basis.”
    - [x] (g) Lower confidence interval on the trend, in original units column – change to the same text that is currently used for the column Upper confidence interval on the trend, in original units
    - [x] (h) Reported confidence interval column -- add a hover with the same text that is currently used for the column Upper confidence interval on the trend, in original units
- [x] 18. Trend results table – the column “Trend in original units” should be “Not available” for all aquatic ecology constituents.
- [x] 19. Table Download – Please follow these steps to see if you can replicate what I am seeing (I am using Chrome, not sure if that matters.)  Refresh the cache.  Then go to Pesticides > Atrazine. Select site 06713500 Cherry Creek in Colorado (it is right next to Denver).  Under the trends table, you’ll see the right results… for a bunch of pesticides and ecology metrics (no WRTDS constituents).  Download the table.  That file looks fine in excel.  Now switch to Nutrients > Total Phosphorus.  Select site 01646580 Potomac River in Washington DC.   Under the trends table, you’ll see the right results…for a bunch of WRTDS constituents and some pesticides.   Download the table.  When I do this, I get two files.  That’s the first problem.  The second problem is that the files (both with the name 01646580_trend_results) have different contents.  The first file to be downloaded has the previous results from Cherry Creek in Denver.  The second file to be downloaded has the correct results for the Potomac River.  I have seen what I think is a variation on this several times when testing the Download functionality today.
- [x] 20. Graphs – for WRTDS.  I’m sure you are already aware of this… The Science base link is still not working.
 
## Future Request
- [x] 21.  Add watershed boundary when a user selects a site.  (Nick and I talked about this one, and it’s is a second-tier need that he’ll try to get to if time allows after everything else).

**Comment by njestes** [comment]
checked 21. already another open issue

**Comment by njestes** [comment]
checked 16. already another open issue

**Comment by HansVraga** [comment]
checking 20 in favor of #135 - with that, this one is done.
