### ISSUE TITLE
FAQ updates

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/nawqa-sw-trends#170]
- [x] FAQ #20 – Change this entirely to “For a given site and trend period, the direction and likelihood of pesticide trends will be the same for concentration and load.  The graphs for will be the same for concentration and load, since both are derived from the same model. The magnitude of the trends also will be the same for concentration and load, when reported in percent.  The magnitude of the trends will be different for concentration and load, when reported in original units.  Using the SEAWAVE-Q model for pesticides, when comparing the trend in percent, the trend in flow-normalized annual load cannot be different mathematically from the trend in flow-normalized annual concentration when there is no trend in flow. This is a computational constraint of the SEAWAVE-Q model.  A different model – Weighted Regressions on Time, Discharge, and Season (WRTDS) – was used for the other water-quality constituents (see FAQ #11).  One attribute of the WRTDS model is that it allows the trend in flow-normalized concentration to be different in magnitude or opposite in direction from trends in flow-normalized load (Hirsch and De Cicco, 2015). For example, if there were large decreases in point source inputs of a pollutant but increases in nonpoint sources associated with high-flow events, then we might see a downward trend in concentration but an upward trend in flux.  But the WRTDS model was not used with pesticides, because SEAWAVE-Q was specifically developed to address a number of difficulties often found in pesticide data, such as strong seasonality in response to use patterns, high numbers of concentrations below laboratory reporting levels, complex relations between streamflow and concentration, and intermittent or changing sampling frequencies (Vecchia and others, 2008) (see FAQ #13). “

- [x] In FAQ #10, at the end, please add:

You also can download the land-use data shown in the Map Layers option through the following U.S. Geological Survey report:

Falcone, J.A., 2015, U.S. conterminous wall-to-wall anthropogenic land use trends (NWALT), 1974–2012: U.S. Geological Survey Data Series 948, 33 p.

- [x] In FAQs, (FAQ #2, #24, and #26) update all occurrences of the citation of Oelsner and others (2017) to the following:

Oelsner, G.P., Sprague, L.A., Murphy, J.C., Zuellig, R.E., Johnson, H.M., Ryberg, K.R., Falcone, J.A., Stets, E.G., Vecchia, A.V., Riskin, M.L., De Cicco, L.A., Mills, T.J., and Farmer, W.H., 2017, Water- Quality Trends in the Nation's Rivers and Streams 1972-2012-Data Preparation, Statistical Methods, and Trend Results: U.S. Geological Survey Scientific Investigations Report 2017-5006, in press.

- [x] FAQ #24: replace the mapper citation with Sprague, L.A., 2017, Water-quality changes in the Nation's streams and rivers: U.S. Geological Survey Web Page, http://nawqatrends.wim.usgs.gov/swtrends.

- [x] In FAQ #21, after the sentence “For pesticides (from Ryberg and Vecchi, 2013):” Please add as a new line with no bullet (note the hyperlink) These graphs show a parameter code for each pesticide contained in the graphs.  A definition for these parameter codes is available from the parameter code dictionary for the U.S Geological Survey’s National Water Information System (NWIS) data base.

- [x] Please add a new FAQ as FAQ #22.  This will bump all subsequent FAQs up by one number. New FAQ #22:
Is it correct that for a given constituent at a given site, the graphs are the same for concentration and load and for different trend periods?

For nutrients, sediment, salinity, major ions, carbon, and pesticides, the graphs are the same for concentration and load for a given trend period.  This is because the concentration and trend results were obtained from the same model.  For nutrients, sediment, salinity, major ions, and carbon (but not for pesticides), the concentration and load graphs also will be the same for different trend periods.  For these constituents, the same model was used to obtain trend results for all available time periods.  For pesticides, a different model was used for the 1992-2012 and the 2002-2012 trend period, so these graphs will be different.

- [x] In FAQ #18: Change the entire text to the following:

A likelihood-based approach is used to report these trend results. When the trend is "likely up" or “likely down”, the trend likelihood value associated with the trend is between 0.85 and 1.0—in other words, the chance of the trend occurring in the specified direction is at least an 85 out of 100. When the trend is "somewhat likely up" or “somewhat likely down”, the trend likelihood value associated with the trend is between 0.7 and 0.85—in other words, the chance of the trend occurring in the specified direction is between 70 and 85 out of 100. When the trend is "about as likely as not", the trend likelihood value associated with the trend is less than 0.7—in other words,  the chance of the trend being either upward or downward is less than 70 out of 100.

This likelihood-based approach is used as an alternative to the null-hypothesis signi­ficance testing (NHST) approach that is often used when reporting water-quality trends. The likelihood-based approach gives people more intuitive information on the certainty of a trend estimate, and provides more evidence of a growing problem or initial clean-up successes.  Consider an example where the chance of an upward trend in nitrate concentrations at a site is 80 out of 100 (a trend likelihood value of 0.80). Using the NHST approach and a traditional alpha value of either 0.05 or 0.1, the trend would be reported as nonsignifi­cant. Using the likelihood-based approach, the trend would be reported instead as "somewhat likely up". The NHST approach could lead to a false sense of security because it indicates that there isn't strong proof of a growing problem. The likelihood-based approach indicates instead that it is somewhat likely conditions in the stream are not improving, giving people more information to use when making decisions about watershed management.

For more information on the philosophy of the likelihood-based approach, please see Hirsch and others (2015), "A bootstrap method for estimating uncertainty of water quality trends", at http://dx.doi.org/10.1016/j.envsoft.2015.07.017.  Trend likelihood values for nutrients, sediment, salinity, major ions, and carbon were determined using the bootstrap approach in that same report. Trend likelihood values for pesticides and aquatic ecology metrics were determined using the p-value reported from their respective trend tests, using the equation 1-(p-value/2).  See Vecchia and others (2008), “Modeling Variability and Trends in

Pesticide Concentrations in Streams”, at http://onlinelibrary.wiley.com/doi/10.1111/j.1752-1688.2008.00225.x/pdf for more information on calculating p-values in the pesticide models.  See Oelsner, G.P., Sprague, L.A., Murphy, J.C., Zuellig, R.E., Johnson, H.M., Ryberg, K.R., Falcone, J.A., Stets, E.G., Vecchia, A.V., Riskin, M.L., De Cicco, L.A., Mills, T.J., and Farmer, W.H., 2017, Water- Quality Trends in the Nation's Rivers and Streams 1972-2012-Data Preparation, Statistical Methods, and Trend Results: U.S. Geological Survey Scientific Investigations Report 2017-5006, in press. for more information on calculating p-values in the ecology models.
