### ISSUE TITLE
FAQs issues

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/nawqa-sw-trends#188]
- [x] FAQ #8—please change “518 different organizations” to “608 different organizations”.

- [x] In FAQ #10, there is a funny character at the end (should be a hyphen).

- [x] FAQ #13, there are two funny characters in the third paragraph (should be dual hyphens, aka --).

- [x] FAQ #14, there is a funny character in the middle (just needs to be deleted so this looks like ”e.g. mg/L or µg/L”).

- [x] In FAQ #18: there are 7 funny characters in the first paragraph (should be quotes around “likely down” and “somewhat likely down” and should be dual hyphens, aka --, before each “in other words”), two in the second paragraph (that weird thing with the letter f again), and two in the third paragraph (should be quotes).  Also, the first sentence of the second paragraph is missing a capital T: “This likelihood-based approach is used ….”.

- [x] FAQ #20 – My bad! Please take out the “for” in the second sentence (The graphs for will be the same for concentration and load, since both are derived from the same model.)  Also there are two funny characters in this FAQ (should be dual hyphens, aka --).

- [x] In FAQ #21, there is a funny character in the new hyperlink text (should be an apostrophe).

- [x] In FAQ #23, there are two funny characters in the first sentence of the second paragraph (should be dual hyphens, aka --).

- [x] In FAQ #27, there are funny characters in the citations for Ryberg (2014), Ryberg (2010), Sprague (2017), Sullivan (2009) and Vecchia (2008) (should be a hyphens).
