### ISSUE TITLE
last editorial changes?

### ISSUE THREAD

**Issue by njestes** [USGS-WiM/nawqa-sw-trends#194]
- [x] Trend tables -- hover text for Trend Likelihood—there is a funny character in there (should be a quote)

- [x] In FAQ #18: there are two funny characters in the second paragraph (that weird thing with the letter f again, in the first sentence in the word “significance” and in the fourth sentence in the word “nonsignificant”).  

- [x] In FAQ #18: the first sentence of the second paragraph is missing a capital T: “This likelihood-based approach is used ….”.

- [x] FAQ #20 – Please take out the “for” in the second sentence (The graphs for will be the same for concentration and load, since both are derived from the same model.)  

- [x] In About > Learn More: After the first table, in the new text about the parameter code dictionary, the semi colon should be an apostrophe.

- [x] User Guide -> Explanation: There are two funny characters in the second paragraph (that weird thing with the letter f again, in the first sentence in the word “significance” and in the fourth sentence in the word “nonsignificant”). 

- [x] User Guide -> Explanation:  Remove the hard break between “… Trend in” and “Pesticide Concentrations….” between the current third and fourth paragraph.  (That should all be one paragraph)
